@echo off
rem =======================================================
rem  CASWebDec Database Setup Script (Windows .bat) - FIXED
rem  - Creates database, user and grants privileges in MariaDB
rem  - Avoids unescaped parentheses that break cmd grouped echo
rem =======================================================
setlocal DISABLEDELAYEDEXPANSION

echo ==========================================
echo      CASWebDec Database Setup Script
echo ==========================================
echo.

:: --- CONFIGURATION (edit as needed) ---
set "DB_NAME=app"
set "APP_USER=coretally_app"
set "APP_PASS=Q9v!eF2pC7x#rUaL"
set "MYSQL_EXE=C:\Program Files\MariaDB 12.1\bin\mysql.exe"

:: --- OPTIONAL: Prompt for APP_PASS interactively (uncomment if you prefer) ---
:: echo.
:: set /p "APP_PASS=Enter password to assign to the new user %APP_USER%: "

:: --- PATH CHECK ---
if not exist "%MYSQL_EXE%" (
    echo [ERROR] MySQL/MariaDB executable not found at:
    echo " %MYSQL_EXE% "
    echo.
    echo Please verify the path in the script configuration.
    pause
    exit /b 1
)

echo.
echo [INFO] You will be prompted for the MariaDB ROOT password to authorize this setup.
echo.

:: --- Escape single quotes in APP_PASS for safe SQL literal embedding ---
:: Replace single quote ' with two single quotes '' (SQL literal escaping)
set "APP_PASS_ESC=%APP_PASS:'=''%"

:: --- Prepare temporary SQL file ---
:: Use current directory instead of TEMP to avoid permission/antivirus issues
set "TMP_SQL=%~dp0create_%DB_NAME%_%RANDOM%.sql"

echo [DEBUG] Attempting to create SQL file at: %TMP_SQL%
echo.

(
    echo /* CASWebDec DB setup - autogenerated, remove file after use */
    echo CREATE DATABASE IF NOT EXISTS `%DB_NAME%` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    echo CREATE USER IF NOT EXISTS '%APP_USER%'@'localhost' IDENTIFIED BY '%APP_PASS_ESC%';
    echo GRANT ALL PRIVILEGES ON `%DB_NAME%`.* TO '%APP_USER%'@'localhost';
    echo -- Also grant for 127.0.0.1 ^(optional^)
    echo CREATE USER IF NOT EXISTS '%APP_USER%'@'127.0.0.1' IDENTIFIED BY '%APP_PASS_ESC%';
    echo GRANT ALL PRIVILEGES ON `%DB_NAME%`.* TO '%APP_USER%'@'127.0.0.1';
    echo FLUSH PRIVILEGES;
) > "%TMP_SQL%" 2>&1

if not exist "%TMP_SQL%" (
    echo.
    echo [ERROR] Failed to write temporary SQL file: %TMP_SQL%
    echo Possible causes:
    echo  - Current directory is not writable ^(permissions or antivirus locking files^)
    echo  - Path contains invalid characters
    echo  - Special characters in password causing redirection issues
    echo.
    echo Try running the script as Administrator.
    pause
    exit /b 1
)

echo [DEBUG] Temporary SQL file created: %TMP_SQL%
echo.
echo [INFO] Running SQL on MariaDB server...
echo.

:: --- EXECUTION ---
:: Note: -p will prompt you for the root password (safer than passing it on command line)
"%MYSQL_EXE%" -u root -p < "%TMP_SQL%"
set "MYSQL_RC=%ERRORLEVEL%"

:: --- CLEANUP ---
if exist "%TMP_SQL%" del /f /q "%TMP_SQL%" >nul 2>&1

if %MYSQL_RC% NEQ 0 (
    echo.
    echo [ERROR] Setup failed (mysql returned exit code %MYSQL_RC%).
    echo Please check:
    echo  - the root password you entered
    echo  - connectivity to the MariaDB server
    echo  - that the MariaDB server is running
    echo.
    pause
    exit /b %MYSQL_RC%
) else (
    echo.
    echo [SUCCESS] Database and user created successfully!
    echo.
    echo -------------------------------------------------------
    echo PLEASE UPDATE YOUR config.py / environment:
    echo DATABASE_URL = "mysql+pymysql://%APP_USER%:REDACTED@localhost/%DB_NAME%?charset=utf8mb4"
    echo (Replace REDACTED with the app password or set as an environment variable)
    echo -------------------------------------------------------
)

pause
endlocal